const CREATE_INDIVIDUAL = 'CREATE_INDIVIDUAL';
const CREATE_CURSILLO = 'CREATE_CURSILLO';
const CREATE_PARISH = 'CREATE_PARISH';
const LOOKUP_INDIVIDUAL = 'LOOKUP_INDIVIDUAL';
const LOOKUP_CURSILLO = 'LOOKUP_CURSILLO';
const LOOKUP_PARISH = 'LOOKUP_PARISH';

export { 
  CREATE_INDIVIDUAL,
  CREATE_CURSILLO,
  CREATE_PARISH,
  LOOKUP_INDIVIDUAL,
  LOOKUP_CURSILLO,
  LOOKUP_PARISH,
};
